services:
  - type: web
    name: purplebot2
    runtime: node
    plan: free
    region: frankfurt  
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.x
    autoDeploy: true
